// <auto-generated />
using BuilderScenario.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuilderScenario.Infrastructure.Migrations
{
    [DbContext(typeof(ScenarioDbContext))]
    partial class ScenarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("BuilderScenario.Core.Entities.ActionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ActionGroups");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StepItemId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.StepItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionGroupId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.ActionGroup", b =>
                {
                    b.HasOne("BuilderScenario.Core.Entities.Scenario", null)
                        .WithMany("Groups")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.ActionItem", b =>
                {
                    b.HasOne("BuilderScenario.Core.Entities.StepItem", null)
                        .WithMany("Actions")
                        .HasForeignKey("StepItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.StepItem", b =>
                {
                    b.HasOne("BuilderScenario.Core.Entities.ActionGroup", null)
                        .WithMany("Steps")
                        .HasForeignKey("ActionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.ActionGroup", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.Scenario", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("BuilderScenario.Core.Entities.StepItem", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
